// This file is generated by Gemini.

'use server';

/**
 * @fileOverview A pizza suggestion AI agent.
 *
 * - generatePizza - A function that handles the pizza suggestion process.
 * - GeneratePizzaInput - The input type for the generatePizza function.
 * - GeneratePizzaOutput - The return type for the generatePizza function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePizzaInputSchema = z.object({
  preferences: z
    .string()
    .describe('The pizza preferences of the user, including favorite toppings, flavors, and dietary restrictions.'),
});
export type GeneratePizzaInput = z.infer<typeof GeneratePizzaInputSchema>;

const GeneratePizzaOutputSchema = z.object({
  pizzaSuggestion: z.string().describe('A unique pizza suggestion based on the user preferences.'),
  reasoning: z.string().describe('The reasoning behind the pizza suggestion, explaining why it matches the user preferences.'),
});
export type GeneratePizzaOutput = z.infer<typeof GeneratePizzaOutputSchema>;

export async function generatePizza(input: GeneratePizzaInput): Promise<GeneratePizzaOutput> {
  return generatePizzaFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePizzaPrompt',
  input: {schema: GeneratePizzaInputSchema},
  output: {schema: GeneratePizzaOutputSchema},
  prompt: `You are a creative pizza chef, skilled at creating new and exciting pizza combinations.

  A user has provided their pizza preferences. Based on these preferences, you will suggest a unique pizza combination, and explain your reasoning for the suggestion.

  User Preferences: {{{preferences}}}
  `,
});

const generatePizzaFlow = ai.defineFlow(
  {
    name: 'generatePizzaFlow',
    inputSchema: GeneratePizzaInputSchema,
    outputSchema: GeneratePizzaOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
